# There are still parts of the project using python2.7 so it's a good idea
# to check if it works at all

name: pybikes

env:
  PYBIKES_CYCLOCITY: ${{ secrets.PYBIKES_CYCLOCITY }}
  PYBIKES_ECOBICI_BA_CLIENT_ID: ${{ secrets.PYBIKES_ECOBICI_BA_CLIENT_ID }}
  PYBIKES_ECOBICI_BA_CLIENT_SECRET: ${{ secrets.PYBIKES_ECOBICI_BA_CLIENT_SECRET }}
  PYBIKES_BYSYKKEL: ${{ secrets.PYBIKES_BYSYKKEL }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: test (2.7)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 2.7
      uses: MatteoH2O1999/setup-python@v1
      with:
        python-version: '2.7'
        allow-build: info
        cache-build: true
    - name: Install dependencies
      run: make install
    - name: lint
      run: make lint
    - name: test
      run: make test
    - name: test update
      run: |
        T_FLAGS="-n 10 --junitxml=report/junit.xml --tb=native"
        # allowed to fail for test runs
        make test-update T_FLAGS+="$T_FLAGS" || true
