name: pybikes

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: make install
    - name: lint
      run: make lint
    - name: test
      run: |
        T_FLAGS="-n 10 --junitxml=report/junit.xml"

        # json report does not support 2.7
        if [[ "${{ matrix.python-version }}" != "2.7" ]]; then
          T_FLAGS="$T_FLAGS --json-report --json-report-file=report/report.json"
        fi

        make test T_FLAGS+="$T_FLAGS"
    - name: summary
      if: (success() || failure()) && matrix.python-version != '2.7'
      run: |
          ./utils/report.py report/report.json --summary >> $GITHUB_STEP_SUMMARY
