name: pybikes

env:
  PYBIKES_CYCLOCITY: ${{ secrets.PYBIKES_CYCLOCITY }}
  PYBIKES_ECOBICI_BA_CLIENT_ID: ${{ secrets.PYBIKES_ECOBICI_BA_CLIENT_ID }}
  PYBIKES_ECOBICI_BA_CLIENT_SECRET: ${{ secrets.PYBIKES_ECOBICI_BA_CLIENT_SECRET }}
  PYBIKES_BYSYKKEL: ${{ secrets.PYBIKES_BYSYKKEL }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: make install
    - name: lint
      run: make lint
    - name: test
      run: make test
    - name: test update
      run: |
        T_FLAGS="-n 10 --junitxml=report/junit.xml --tb=native"
        T_FLAGS="$T_FLAGS --json-report --json-report-file=report/report.json"
        # allowed to fail for test runs
        make test-update T_FLAGS+="$T_FLAGS" || true
    # Only run summary once
    - name: summary
      if: (success() || failure()) && matrix.python-version == '3.8'
      run: |
          ./utils/report.py report/report.json >> $GITHUB_STEP_SUMMARY
